In [2]:
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [4]:
df['salary_year_avg'].median()

115000.0

In [5]:
df['salary_year_avg'].min()

15000.0

In [6]:
min_salary = df['salary_year_avg'].idxmin()

In [8]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [9]:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [10]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [11]:
df.groupby('job_title_short')['salary_year_avg'].mean().sort_values(ascending=False)

job_title_short
Senior Data Scientist        154206.292996
Senior Data Engineer         145840.611624
Data Scientist               135988.837171
Data Engineer                130125.604250
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Software Engineer            113393.760054
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Business Analyst              91082.612833
Name: salary_year_avg, dtype: float64

In [ ]:
df.groupby('job_title_short')['salary_year_avg'].min().sort_values()

job_title_short
Data Engineer                15000.0
Business Analyst             16500.0
Data Analyst                 25000.0
Data Scientist               27000.0
Software Engineer            28000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Cloud Engineer               42000.0
Senior Data Scientist        45000.0
Name: salary_year_avg, dtype: float64

In [14]:
df.groupby('job_title_short')['salary_year_avg'].max().sort_values(ascending=False)

job_title_short
Data Scientist               960000.0
Senior Data Scientist        890000.0
Data Analyst                 650000.0
Data Engineer                525000.0
Senior Data Analyst          425000.0
Senior Data Engineer         425000.0
Business Analyst             387460.0
Software Engineer            375000.0
Machine Learning Engineer    325000.0
Cloud Engineer               280000.0
Name: salary_year_avg, dtype: float64

In [15]:
df.groupby(['job_title_short', 'job_location'])['salary_year_avg'].mean()

job_title_short    job_location
Business Analyst   's-Graveland, Netherlands                          NaN
                   's-Hertogenbosch, Netherlands                      NaN
                   10th of Ramadan City, Egypt                        NaN
                   6th of October City, Egypt                         NaN
                   A Coruña, Spain                                    NaN
                                                                       ..
Software Engineer  Ümraniye, Elmalıkent, Ümraniye/İstanbul, Türkiye   NaN
                   İstanbul, Turkey                                   NaN
                   İstanbul, Türkiye                                  NaN
                   Łódź, Poland                                       NaN
                   Žilina, Slovakia                                   NaN
Name: salary_year_avg, Length: 42721, dtype: float64

In [16]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [17]:
df.groupby('job_title_short')['salary_year_avg'].agg(['mean', 'min', 'max'])

                                    mean      min       max
job_title_short
Business Analyst            91082.612833  16500.0  387460.0
Cloud Engineer             111268.453846  42000.0  280000.0
Data Analyst                93841.907854  25000.0  650000.0
Data Engineer              130125.604250  15000.0  525000.0
Data Scientist             135988.837171  27000.0  960000.0
Machine Learning Engineer  126774.315972  30000.0  325000.0
Senior Data Analyst        113911.363665  30000.0  425000.0
Senior Data Engineer       145840.611624  35000.0  425000.0
Senior Data Scientist      154206.292996  45000.0  890000.0
Software Engineer          113393.760054  28000.0  375000.0