In [1]:
from datasets import load_dataset

C:\Users\MIHIR\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
dataset = load_dataset('lukebarousse/data_jobs')

In [4]:
df = dataset['train'].to_pandas()

In [8]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [7]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [9]:
df[['job_title', 'job_location', 'search_location']].head(10)

,job_title,job_location,search_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT","Texas, United States"
1,Data Analyst,"Guadalajara, Jalisco, Mexico",Mexico
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",Germany
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX","Texas, United States"
4,Data Engineer- Sr Jobs,"Washington, DC",Sudan
5,GCP Data Engineer,Anywhere,Georgia
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI","Florida, United States"
7,Data Engineer,Anywhere,Romania
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",Denmark
9,Data Scientist II,Anywhere,"New York, United States"

In [10]:
df.iloc[90]

job_title_short                                             Data Scientist
job_title                                                   Data Scientist
job_location                                                     Australia
job_via                                                via BeBee Australia
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                  Australia
job_posted_date                                        2023-11-25 13:12:03
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                      Australia
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                           Concurrent Technologies Corporation
job_skills               ['python', 'sql', 'r', 'java', 'bash', 'react'...
job_type_skills          {'analyst_tools': ['tableau'], 'libraries': ['...
Name: 90, dtype: object

In [ ]:
df.iloc[90:100] # Slicing

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
90,Data Scientist,Data Scientist,Australia,via BeBee Australia,Full-time,False,Australia,2023-11-25 13:12:03,False,False,Australia,None,NaN,NaN,Concurrent Technologies Corporation,"['python', 'sql', 'r', 'java', 'bash', 'react'...","{'analyst_tools': ['tableau'], 'libraries': ['..."
91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,None,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
93,Data Analyst,IT Finance / TBM Data Analyst - Remote | WFH,Anywhere,via LinkedIn,Full-time,True,"New York, United States",2023-06-10 13:00:05,False,False,United States,None,NaN,NaN,Get It Recruit - Information Technology,"['oracle', 'azure', 'power bi', 'excel', 'word...","{'analyst_tools': ['power bi', 'excel', 'word'..."
94,Data Engineer,Data Engineer - Cloud Operations,"Lehi, UT",via LinkedIn,Full-time,False,"Texas, United States",2023-03-18 13:08:17,False,False,United States,None,NaN,NaN,Adobe,"['javascript', 'python', 'sql', 'aws', 'azure'...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."
95,Data Engineer,Data Engineer,"Mumbai, Maharashtra, India",via Crimsoniteam.freshteam.com,Full-time,False,India,2023-07-31 13:35:48,False,False,India,None,NaN,NaN,Crimson Interactive Inc,"['nosql', 'mongodb', 'mongodb', 'elasticsearch...","{'analyst_tools': ['tableau'], 'databases': ['..."
96,Data Engineer,Data Engineer,"Torrance, CA",via LinkedIn,Full-time,False,Sudan,2023-06-15 14:03:55,False,False,Sudan,None,NaN,NaN,King's Hawaiian,"['sql', 'r', 'python', 'sql server', 'azure', ...","{'analyst_tools': ['sap'], 'cloud': ['azure', ..."
97,Data Analyst,"Systems & Data Analyst - Exploitation, Missing...",United Kingdom,via Totaljobs,Full-time and Contractor,False,United Kingdom,2023-12-04 13:14:01,True,False,United Kingdom,None,NaN,NaN,Solihull Metropolitan Borough Council,None,None
98,Senior Data Engineer,Senior Data Engineer (AWS),"Toronto, ON, Canada",via SmartRecruiters Job Search,Full-time,False,Canada,2023-09-01 13:42:05,True,False,Canada,None,NaN,NaN,MUFG Investor Services,"['python', 'aws', 'databricks', 'spark']","{'cloud': ['aws', 'databricks'], 'libraries': ..."
99,Data Engineer,Senior/Staff Data Engineer – Apache Spark (Jav...,"Miami, FL",via LinkedIn,Full-time,False,"California, United States",2023-09-12 13:09:28,False,False,United States,None,NaN,NaN,Agoda,"['scala', 'java', 'golang', 'sql', 'react', 's...","{'libraries': ['react', 'spark', 'hadoop'], 'o..."

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [13]:
df.job_title_short.unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [14]:
df.job_title_short == 'Data Scientist'

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_title_short, Length: 785741, dtype: bool

In [15]:
df[df.job_title_short == 'Data Scientist']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
17,Data Scientist,Data Science Team Lead,"Laurel, MD",via APL Careers - Johns Hopkins University App...,Full-time,False,Georgia,2023-06-13 13:25:17,False,True,United States,None,NaN,NaN,Johns Hopkins Applied Physics Laboratory,"['go', 'apl', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,None,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,None,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear..."
21,Data Scientist,Stage - data scientist – génération ia de donn...,"Asnières-sur-Seine, France",via Jobijoba,Full-time,False,France,2023-02-23 13:41:21,False,False,France,None,NaN,NaN,Credit Agricole,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785689,Data Scientist,Data Scientist -50065385,Israel,via LinkedIn,Full-time,False,Israel,2023-01-30 06:36:07,False,False,Israel,None,NaN,NaN,Phoenix Holdings קבוצת הפניקס,['sql'],{'programming': ['sql']}
785690,Data Scientist,Customer Master Data Specialist,"Makati, Metro Manila, Philippines",via Trabajo.org,Full-time,False,Philippines,2023-01-18 06:16:42,False,False,Philippines,None,NaN,NaN,Henkel,"['vba', 'sap', 'word', 'powerpoint', 'excel']","{'analyst_tools': ['sap', 'word', 'powerpoint'..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785697,Data Scientist,Data Science Python modelling,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-01-16 06:12:27,False,False,India,None,NaN,NaN,Live Connections,"['python', 'sql', 'r', 'power bi', 'tableau', ...","{'analyst_tools': ['power bi', 'tableau', 'wor..."
785725,Data Scientist,Analytics Engineer,Jerman,melalui Startup Jobs,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,Planet,"['sql', 'bigquery', 'gdpr', 'git', 'gitlab', '...","{'cloud': ['bigquery'], 'libraries': ['gdpr'],..."

In [21]:
df[(df.job_title_short == 'Data Scientist') & (df.job_work_from_home == True)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
24,Data Scientist,Data Scientist (DataLab Team),Anywhere,via LinkedIn,Full-time,True,Serbia,2023-06-27 13:46:46,False,False,Serbia,None,NaN,NaN,Semrush,['python'],{'programming': ['python']}
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
119,Data Scientist,Global Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-03-13 13:06:29,False,False,United States,None,NaN,NaN,Kimberly-Clark,"['sql', 'r', 'python', 'azure', 'snowflake', '...","{'analyst_tools': ['sap', 'powerpoint', 'excel..."
136,Data Scientist,Mid/ Senior Data Scientist with NLP,Anywhere,via LinkedIn,Full-time,True,Poland,2023-12-21 13:10:55,False,False,Poland,None,NaN,NaN,Trans.eu Group,"['python', 'sql', 'snowflake', 'aws', 'scikit-...","{'cloud': ['snowflake', 'aws'], 'libraries': [..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785155,Data Scientist,Research Analyst,Anywhere,via LinkedIn,Full-time,True,India,2023-01-02 06:29:45,False,False,India,None,NaN,NaN,Ecosystm,None,None
785302,Data Scientist,Principal Data Scientist - Full-time,Anywhere,via Snagajob,Full-time,True,"Florida, United States",2023-01-28 06:08:09,False,True,United States,None,NaN,NaN,Jobot,"['python', 'sql']","{'programming': ['python', 'sql']}"
785434,Data Scientist,Training and Internship in Data Science,Anywhere,via LinkedIn,None,True,India,2023-01-24 06:10:58,False,False,India,None,NaN,NaN,Corizo,None,None
785645,Data Scientist,Data Science Intern,Anywhere,via LinkedIn,Internship,True,India,2023-01-20 06:51:23,False,False,India,None,NaN,NaN,TwiLearn EduTech Pvt. Ltd.,"['python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
785654,Data Scientist,Data Science Intern,Anywhere,via LinkedIn,None,True,India,2023-01-31 06:11:46,False,False,India,None,NaN,NaN,Corizo,['zoom'],{'sync': ['zoom']}